import React from "react";
import { useTranslation } from "react-i18next";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Checkbox from "@mui/material/Checkbox";
import CircularProgress from "@mui/material/CircularProgress";
import FormControlLabel from "@mui/material/FormControlLabel";
import IconButton from "@mui/material/IconButton";
import Paper from "@mui/material/Paper";
import Skeleton from "@mui/material/Skeleton";
import Stack from "@mui/material/Stack";
import Tooltip from "@mui/material/Tooltip";
import Typography from "@mui/material/Typography";
import RefreshIcon from "@mui/icons-material/Refresh";
import { UnauthorizedError } from "../../api/client";
import { captchaApi, type CaptchaPlace, type CaptchaSettings } from "../../api/captcha";
import SectionHeader from "../../components/SectionHeader";
import { invalidateCaptchaSettings } from "../../hooks/useCaptchaSettings";

type Props = {
  onUnauthorized?: () => void;
};

const PLACES: CaptchaPlace[] = ["login", "register", "import"];

/** Administration > Captcha: where the web app asks for an image captcha (all off by default).
 *  Each box saves as soon as it's ticked. The captcha itself is generated by the backend (see
 *  services/captchaService.ts); Thingport Grab, the browser extension, is never asked for one. */
export default function CaptchaPage({ onUnauthorized }: Props) {
  const { t } = useTranslation("app");
  const [settings, setSettings] = React.useState<CaptchaSettings | null>(null);
  const [saving, setSaving] = React.useState<CaptchaPlace | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [preview, setPreview] = React.useState<string | null>(null);

  const loadPreview = React.useCallback(() => {
    setPreview(null);
    captchaApi.get().then((c) => setPreview(c.image), () => setPreview(null));
  }, []);

  React.useEffect(() => {
    let active = true;
    captchaApi.getSettings().then(
      (value) => { if (active) setSettings(value); },
      () => { if (active) setError(t("adminSettings.captcha.loadFailed")); },
    );
    loadPreview();
    return () => { active = false; };
  }, [t, loadPreview]);

  const toggle = async (place: CaptchaPlace, enabled: boolean) => {
    if (!settings) return;
    const previous = settings;
    setSettings({ ...settings, [place]: enabled });
    setSaving(place);
    setError(null);
    try {
      setSettings(await captchaApi.updateSettings({ [place]: enabled }));
      invalidateCaptchaSettings();
    } catch (err) {
      if (err instanceof UnauthorizedError) {
        onUnauthorized?.();
        return;
      }
      setSettings(previous);
      setError(err instanceof Error ? err.message : t("adminSettings.captcha.saveFailed"));
    } finally {
      setSaving(null);
    }
  };

  return (
    <Stack spacing={3} sx={{ maxWidth: 720 }}>
      <SectionHeader title={t("adminSettings.captcha.placesHeading")} subtitle={t("adminSettings.captcha.subtitle")} />
      <Paper variant="outlined" sx={{ p: 2.5 }}>
        <Stack spacing={1.5}>
          {PLACES.map((place) => (
            <Box key={place}>
              <Stack direction="row" spacing={1} alignItems="center">
                <FormControlLabel
                  control={
                    <Checkbox
                      checked={settings?.[place] ?? false}
                      disabled={!settings || saving !== null}
                      onChange={(e) => void toggle(place, e.target.checked)}
                    />
                  }
                  label={t(`adminSettings.captcha.places.${place}.label`)}
                />
                {saving === place && <CircularProgress size={16} />}
              </Stack>
              <Typography variant="body2" color="text.secondary" sx={{ ml: 4 }}>
                {t(`adminSettings.captcha.places.${place}.help`)}
              </Typography>
            </Box>
          ))}
          {error && <Alert severity="error" onClose={() => setError(null)}>{error}</Alert>}
        </Stack>
      </Paper>

      <Paper variant="outlined" sx={{ p: 2.5 }}>
        <Stack spacing={1.5}>
          <Typography variant="subtitle2" fontWeight={600}>{t("adminSettings.captcha.previewHeading")}</Typography>
          <Stack direction="row" spacing={1} alignItems="center">
            <Box sx={{ width: 160, height: 56, borderRadius: 1, overflow: "hidden", border: "1px solid", borderColor: "divider" }}>
              {preview ? (
                <Box component="img" src={preview} alt={t("captcha.imageAlt")} sx={{ width: 160, height: 56, display: "block" }} />
              ) : (
                <Skeleton variant="rectangular" width={160} height={56} />
              )}
            </Box>
            <Tooltip title={t("captcha.newImage")}>
              <IconButton onClick={loadPreview} aria-label={t("captcha.newImage")}><RefreshIcon /></IconButton>
            </Tooltip>
          </Stack>
          <Typography variant="body2" color="text.secondary">{t("adminSettings.captcha.previewHelp")}</Typography>
          <Alert severity="info">{t("adminSettings.captcha.extensionNote")}</Alert>
        </Stack>
      </Paper>
    </Stack>
  );
}
