import React from "react";
import { useTranslation } from "react-i18next";
import Box from "@mui/material/Box";
import IconButton from "@mui/material/IconButton";
import Skeleton from "@mui/material/Skeleton";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Tooltip from "@mui/material/Tooltip";
import Typography from "@mui/material/Typography";
import RefreshIcon from "@mui/icons-material/Refresh";
import { captchaApi, type CaptchaAnswer } from "../api/captcha";

type Props = {
  onChange: (answer: CaptchaAnswer | null) => void;
  disabled?: boolean;
};

/** A captcha image (generated by the backend, see services/captchaService.ts) with a field for
 *  its characters. Reports the id + typed answer through `onChange`, for the caller to send with
 *  the request the captcha guards. Each captcha works once, so after a failed attempt callers
 *  remount this with a new `key` to get a fresh image. */
export default function CaptchaField({ onChange, disabled = false }: Props) {
  const { t } = useTranslation("app");
  const [captcha, setCaptcha] = React.useState<{ id: string; image: string } | null>(null);
  const [answer, setAnswer] = React.useState("");
  const [failed, setFailed] = React.useState(false);
  const onChangeRef = React.useRef(onChange);
  // Only the newest request may update the image -- a slow earlier one mustn't replace it.
  const requestRef = React.useRef(0);

  React.useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  const load = React.useCallback(() => {
    const request = ++requestRef.current;
    setCaptcha(null);
    setAnswer("");
    setFailed(false);
    onChangeRef.current(null);
    captchaApi.get().then(
      (next) => { if (requestRef.current === request) setCaptcha(next); },
      () => { if (requestRef.current === request) setFailed(true); },
    );
  }, []);

  React.useEffect(() => {
    load();
    return () => { requestRef.current += 1; };
  }, [load]);

  const handleAnswer = (value: string) => {
    setAnswer(value);
    onChangeRef.current(captcha ? { captcha_id: captcha.id, captcha_answer: value } : null);
  };

  return (
    <Stack spacing={1}>
      <Stack direction="row" spacing={1} alignItems="center">
        <Box
          sx={{
            width: 160,
            height: 56,
            borderRadius: 1,
            overflow: "hidden",
            border: "1px solid",
            borderColor: "divider",
            flexShrink: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {captcha ? (
            <Box component="img" src={captcha.image} alt={t("captcha.imageAlt")} sx={{ width: 160, height: 56, display: "block" }} />
          ) : failed ? (
            <Typography variant="caption" color="error" sx={{ px: 1, textAlign: "center" }}>{t("captcha.loadFailed")}</Typography>
          ) : (
            <Skeleton variant="rectangular" width={160} height={56} />
          )}
        </Box>
        <Tooltip title={t("captcha.newImage")}>
          <span>
            <IconButton onClick={load} disabled={disabled} aria-label={t("captcha.newImage")}>
              <RefreshIcon />
            </IconButton>
          </span>
        </Tooltip>
      </Stack>
      <TextField
        label={t("captcha.label")}
        value={answer}
        onChange={(e) => handleAnswer(e.target.value)}
        required
        fullWidth
        size="small"
        disabled={disabled || !captcha}
        autoComplete="off"
        slotProps={{ htmlInput: { autoCapitalize: "off", spellCheck: false } }}
      />
    </Stack>
  );
}
