// MakerWorld UI labels in every language it ships (de, en, es, fr, it, ja, ko, pt, ru, sv, zh,
// zh-tw; its other locales show English). Matched on text because class names are build hashes.
// Each set is one key of the site's own translations, readable from any page's
// __NEXT_DATA__ props.pageProps._nextI18Next.initialI18nStore.

/** common.common.noMore: shown under a fully loaded list. */
export const NO_MORE_DATA = new Set([
  "No more data",
  "Keine weiteren Daten",
  "No hay más datos",
  "Aucune donnée disponible",
  "Nessun ulteriore dato",
  "これ以上データはありません",
  "더 이상 데이터 없음",
  "Sem mais dados",
  "Больше данных нет",
  "Inga fler uppgifter",
  "没有更多了~",
  "沒有更多資料",
]);

/** The model page's main button, whose arrow opens the download menu:
 *  common.models.detail.open_in_studio / open_in_bambu_suite / open_in_bambu_handy. */
export const OPEN_IN_APP = new Set([
  "Open in Bambu Studio",
  "Im Bambu Studio öffnen",
  "Abrir en Bambu Studio",
  "Ouvrir dans Bambu Studio",
  "Apri in Bambu Studio",
  "Bambu Studioで開く",
  "Bambu Studio에서 열기",
  "Aberto no Bambu Studio",
  "Открыть в Bambu Studio",
  "Öppet i Bambu Studio",
  "在 Bambu Studio 中打开",
  "在 Bambu Studio 中開啟",
  "Open in Bambu Suite",
  "In der Bambu Suite öffnen",
  "Abrir en Bambu Suite",
  "Ouvert dans la suite Bambu",
  "Apri in Bambu Suite",
  "Bambu Suite で開く",
  "Bambu Suite에서 열기",
  "Aberto na Suíte Bambu",
  "Открыть в Bambu Suite",
  "Öppna i Bambu Suite",
  "在 Bambu Suite 中打开",
  "在 Bambu Suite 中開啟",
  "Open in Bambu Handy",
  "In Bambu Handy öffnen",
  "Abrir en Bambu Handy",
  "Ouvrir dans Bambu Handy",
  "Apri in Bambu Handy",
  "Bambu Handyで開く",
  "Bambu Handy에서 열기",
  "Aberto em Bambu Handy",
  "Открыть в Bambu Handy",
  "Öppna i Bambu Handy",
  "在Bambu Handy中打开",
  "在 Bambu Handy 中開啟",
]);

/** common.models.detail.download_3mf: downloads the selected print profile directly. */
export const DOWNLOAD_3MF = new Set([
  "Download 3MF",
  "3MF herunterladen",
  "Descargar 3MF",
  "Télécharger en 3MF",
  "Scaricare 3MF",
  "3MFをダウンロード",
  "3MF 다운로드",
  "Baixar 3MF",
  "Скачать 3MF",
  "Ladda ner 3MF",
  "下载 3MF",
  "下載 3MF",
]);

/** common.models.detail.download_stl: opens the raw-files dialog (see DOWNLOAD_ALL). */
export const DOWNLOAD_STL = new Set([
  "Download STL/CAD Files",
  "STL/CAD herunterladen",
  "Descargar archivos STL/CAD",
  "Télécharger en STL",
  "Download STL",
  "STL/CAD ファイルのダウンロード",
  "STL/CAD 파일 다운로드",
  "Baixar arquivos STL/CAD",
  "Скачать STL/CAD-файлы",
  "Ladda ner STL",
  "下载 STL/CAD 文件",
  "下載 STL/CAD 檔案",
]);

/** Other model types' download items, and the plain button: download_model_files,
 *  2d_models_download_svg, download_lac, common.common.download. */
export const DOWNLOAD_OTHER = new Set([
  "Download Model Files",
  "Modelldateien herunterladen",
  "Descargar archivos de modelo",
  "Télécharger les Fichiers Modèles",
  "Download file del modello",
  "モデルファイルをダウンロード",
  "모델 파일 다운로드",
  "Baixar arquivos de modelo",
  "Скачать файлы модели",
  "Ladda ner modellfiler",
  "下载模型文件",
  "下載模型檔案",
  "Download SVG Files",
  "SVG-Dateien herunterladen",
  "Descargar archivos SVG",
  "Télécharger les fichiers SVG",
  "Scarica file SVG",
  "SVG ファイルのダウンロード",
  "SVG 파일 다운로드",
  "Baixar arquivos SVG",
  "Скачать SVG-файлы",
  "Ladda ner SVG-filer",
  "下载 SVG",
  "下載 SVG 檔案",
  "Download LAC",
  "LAC herunterladen",
  "Descargar LAC",
  "Télécharger LAC",
  "Scarica LAC",
  "LACをダウンロード",
  "LAC 다운로드",
  "Baixar LAC",
  "Скачать LAC",
  "Ladda ner LAC",
  "下载 LAC",
  "下載 LAC",
  "Download",
  "Herunterladen",
  "Descargar",
  "Télécharger",
  "Scarica",
  "ダウンロード",
  "다운로드",
  "Скачать",
  "Ladda ned",
  "下載",
]);

/** common.models.download_all: the raw-files dialog's button, which downloads a zip of them. */
export const DOWNLOAD_ALL = new Set([
  "Download All",
  "Alles herunterladen",
  "Descargar todo",
  "Télécharger Tout",
  "Download tutto",
  "すべてダウンロード",
  "모두 다운로드",
  "Baixar tudo",
  "Скачать всё",
  "Ladda ner alla",
  "下载所有",
  "全部下載",
]);
